theme: jekyll-theme-cayman
title: Welcome to AAYUSH's Github homepage
discription: Feel free to bookmark this to keep an eye on my project updates
*This text will be italic*
_This will also be italic_

**This text will be bold**
__This will also be bold__

_You **can** combine them_
