title: Aayush
author: Aayush
email: ''
url: aayush9753.github.io
baseurl: ""
description: My Cave [WIP - Building using https://r0m1t.com/]

permalink: /:slug.html

favicon: "assets/images/beluga.jpg"
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
