title: Research Reading Library
description: A personal collection of research papers, articles, and reading notes
lang: en

# SEO settings
tagline: Organized research notes and paper summaries
keywords:
  - research
  - papers
  - notes
  - academic
  - reading list

# Site features
search: true
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: /:title/

# Collections for research content
collections:
  papers:
    output: true
    permalink: /papers/:path/
  notes:
    output: true
    permalink: /notes/:path/
  topics:
    output: true
    permalink: /topics/:path/

# Default settings
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: papers
    values:
      layout: paper
  - scope:
      path: ""
      type: notes
    values:
      layout: note
  - scope:
      path: ""
      type: topics
    values:
      layout: topic

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Simple navigation
menu:
  - title: Home
    url: /
  - title: Papers
    url: /papers/
  - title: Topics
    url: /topics/
  - title: Reading Queue
    url: /queue/
  - title: Search
    url: /search/